Repository prgrms-be-devcourse/NBE4-5-2-Team07, pull requests merged in 2025-03, with the labels that each got.

#27 feat: Open AI API 사용한 가상 면접 챗봇 도입 - be, fe 적용 완료
  backend/build.gradle
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/InterviewAIController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/Message.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/OpenAiService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/ChatRequest.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/ChatResponse.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/InterviewEvaluationDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/InterviewNextDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/InterviewRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/dto/InterviewStartDto.java
  frontend/src/app/api/techInterview/evaluation/route.ts
  frontend/src/app/api/techInterview/next/route.ts
  frontend/src/app/api/techInterview/page.tsx
  frontend/src/app/api/techInterview/start/route.ts
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/app/techInterview/evaluation/page.tsx
Labels: Feature

#46 Feat/#28
  backend/apiV1.json
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemo.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/src/app/components/Header.tsx
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature, Fix

#47 Feat/#28
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
Labels: Feature, Fix

#49 Feat/#28
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/AuthTokenService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/java/NBE4_5_1_7/standard/Ut.java
  backend/src/main/resources/application.yml
Labels: Feature, Fix

#52 Feat/#28
  backend/apiV1.json
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/AuthTokenService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/InterviewAIController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/OpenAiService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/src/app/api/techInterview/evaluation/route.ts
  frontend/src/app/api/techInterview/next/route.ts
  frontend/src/app/api/techInterview/start/route.ts
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/app/techInterview/evaluation/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature, Fix

#54 feat: 회원 정보 API, 로그인 로그아웃 기능(백엔드+프론트)#44
  backend/apiV1.json
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/controller/MemberController.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/Rq.java
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/ClientPage.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/loginMemberStore.tsx
  frontend/src/app/page.tsx
  frontend/src/app/sst.txt
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#59 Feat/#53
  backend/apiV1.json
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/request/InterviewCommentRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/repository/InterviewCommentRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/controller/MemberController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/dto/MemberInfoResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  frontend/src/app/components/Header.tsx
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/login/loginMemberStore.tsx
  frontend/src/app/login/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#61 feat: 메인 페이지 및 컴포넌트 비율 수정
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/ClientPage.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/login/page.tsx
Labels: Fix

#71 Feat/#63
  backend/apiV1.json
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewBookmarkController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/InterviewContent.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/InterviewContentBookmark.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/dto/response/BookmarkResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/repository/BookmarkRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java
  frontend/src/app/components/Header.tsx
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature, Fix

#73 feat: 학습 메모 조회/수정/삭제 API 연동 및 마이페이지 접근 제한
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/request/StudyMemoRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/response/StudyMemoResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/FirstCategory.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoService.java
  frontend/src/app/components/Header.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#81 fix: interview page 원상복구
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/InterviewContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
  backend/src/main/resources/application.yml
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#85 [Refactor] 로그인 후 마이페이지 링크 표시 및 코드 리팩토링 작업 진행
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/dto/request/InterviewCommentRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/repository/InterviewCommentRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/service/InterviewCommentService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/FirstCategory.java
  frontend/src/app/components/Header.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Refactor

#86 fix: 면접 컨텐츠 -> 로그아웃 상태이면, 로그인 화면으로 이동
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/OpenAiService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/src/app/api/techInterview/evaluation/route.ts
  frontend/src/app/api/techInterview/next/route.ts
  frontend/src/app/api/techInterview/start/route.ts
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
Labels: Feature

#89 test: 인터뷰 테스트 코드 #88
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java
  backend/src/test/java/com/java/NBE4_5_1_7/domain/interview/InterviewServiceTest.java
Labels: Test

#90 Feat/#87 면접 컨텐츠 - 좋아요 기능 구현
  backend/build.gradle
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewLikeController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/InterviewContentLike.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/dto/response/InterviewResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/repository/InterviewContentLikeRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewLikeService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/RedissonConfig.java
  backend/src/main/resources/application.yml
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#92 swagger access token 적용
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/OpenApiConfig.java
  backend/src/main/resources/application.yml
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#94 [Feat] 학습 콘텐츠 페이지(관리자) 카테고리 분류와 모달 페이지 추가
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyContentAdminController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/request/StudyContentUpdateRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/FirstCategory.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyContentAdminService.java
  frontend/src/app/admin/questions/page.tsx
  frontend/src/app/admin/studyContent/content.tsx
  frontend/src/app/admin/studyContent/modal/contentDeleteModal.tsx
  frontend/src/app/admin/studyContent/modal/contentDetailModal.tsx
  frontend/src/app/admin/studyContent/modal/contentEditModal.tsx
  frontend/src/app/admin/studyContent/page.tsx
  frontend/src/app/admin/studyContent/sidebar.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/styles/admin/content.module.css
  frontend/src/app/styles/admin/modal/contentDeleteModal.module.css
  frontend/src/app/styles/admin/modal/contentDetailModal.module.css
  frontend/src/app/styles/admin/modal/contentEditModal.module.css
  frontend/src/app/styles/admin/page.module.css
  frontend/src/app/styles/admin/sidebar.module.css
Labels: Feature

#104 refactor:로그인 권한 확인 로직 수정#101
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyContentAdminController.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/Rq.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/InterviewContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/package.json
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Refactor

#106 feat: 면접 질문 관리 페이지(관리자) API 연결
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/controller/InterviewAdminController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/InterviewContent.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/dto/request/InterviewContentAdminRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/entity/dto/response/InterviewContentAdminResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/repository/InterviewContentAdminRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interview/service/InterviewAdminService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyContentAdminController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyContentAdminService.java
  frontend/src/app/admin/interview/content.tsx
  frontend/src/app/admin/interview/modal/interviewDeleteModal.tsx
  frontend/src/app/admin/interview/modal/interviewDetailModal.tsx
  frontend/src/app/admin/interview/modal/interviewEditModal.tsx
  frontend/src/app/admin/interview/page.tsx
  frontend/src/app/admin/interview/sidebar.tsx
  frontend/src/app/admin/studyContent/modal/contentEditModal.tsx
  frontend/src/app/styles/admin/content.module.css
  frontend/src/app/styles/admin/modal/contentDetailModal.module.css
Labels: Feature

#108 [Feat] 관리자와의 채팅 기능 구현
  backend/build.gradle
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatMessageController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/request/ChatRoomRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatMessageResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatRoomResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatPublisher.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatSubscriber.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/interviewComment/controller/InterviewCommentController.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/WebSocketConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/util/LockManager.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#111 Feat/#93 학습 컨텐츠 메모 공유 기능 구현
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/controller/StudyMemoLikeController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/request/StudyMemoCreateRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/dto/response/StudyMemoResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemo.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/entity/StudyMemoLike.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoLikeRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/repository/StudyMemoRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoLikeService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/study/service/StudyMemoService.java
  frontend/src/app/studyContent/memoList/[selectedContentId]/page.tsx
  frontend/src/app/studyContent/studyContentBody.tsx
  frontend/src/app/styles/studyContent.module.css
Labels: Feature

#112 [Fix] 일회성 채팅으로 변경
  backend/build.gradle
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatMessageController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/request/ChatRoomRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatMessageResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/dto/response/ChatRoomResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/model/Message.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatPublisher.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatSubscriber.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/RedisConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/WebSocketConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#116 Feat/#110
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/dto/AddCommentRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/dto/CommentResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/dto/EditCommentRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/entity/Comment.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/repository/CommentRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/controller/CommunityController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/like/dto/LikeResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/like/entity/PostLike.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/like/repository/PostLikeRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/dto/AddPostRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/dto/EditPostRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/dto/PostListResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/dto/PostResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/entity/Post.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/repository/PostRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/service/PostService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/InterviewContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
  backend/src/main/resources/application.yml
  frontend/src/app/community/[postId]/page.tsx
  frontend/src/app/community/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#119 Feat/#117
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/comment/dto/CommentResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/controller/CommunityController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/entity/Post.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/service/PostService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/src/app/community/[postId]/page.tsx
  frontend/src/app/community/page.tsx
  frontend/src/app/community/write/page.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#121 메인 페이지 및 Header 수정
  frontend/package.json
  frontend/src/app/ClientPage.tsx
  frontend/src/app/components/Header.tsx
Labels: Feature

#124 feat: 데이터 등록 모달 페이지 구현
  frontend/src/app/admin/interview/header.tsx
  frontend/src/app/admin/interview/modal/interviewCreateModal.tsx
  frontend/src/app/admin/interview/modal/interviewDetailModal.tsx
  frontend/src/app/admin/interview/page.tsx
  frontend/src/app/admin/studyContent/content.tsx
  frontend/src/app/admin/studyContent/header.tsx
  frontend/src/app/admin/studyContent/modal/contentCreateModal.tsx
  frontend/src/app/admin/studyContent/modal/contentEditModal.tsx
  frontend/src/app/admin/studyContent/page.tsx
  frontend/src/app/styles/admin/content.module.css
  frontend/src/app/styles/admin/header.module.css
  frontend/src/app/styles/admin/modal/contentDetailModal.module.css
  frontend/src/app/styles/admin/page.module.css
  frontend/src/app/styles/admin/sidebar.module.css
Labels: Feature

#125 [Feat] 사용자 측 고객센터 채팅 기능 구현
  .DS_Store
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/main/.DS_Store
  backend/src/main/java/.DS_Store
  backend/src/main/java/com/.DS_Store
  backend/src/main/java/com/java/.DS_Store
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/model/Message.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatPublisher.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  frontend/next.config.ts
  frontend/src/app/chat/ChatWidget.tsx
  frontend/src/app/layout.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#126 Feat/#122
  backend/src/main/java/com/java/NBE4_5_1_7/domain/community/post/service/PostService.java
  frontend/src/app/community/page.tsx
  frontend/src/app/community/write/page.tsx
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/interview/category/page.tsx
  frontend/src/app/interview/keyword/page.tsx
  frontend/src/app/interview/random/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/studyContent/studyContentBody.tsx
  frontend/src/app/studyContent/studyContentCategory.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature

#131 Feat/#128
  frontend/package.json
  frontend/src/app/admin/studyContent/content.tsx
  frontend/src/app/admin/studyContent/header.tsx
  frontend/src/app/admin/studyContent/modal/contentCreateModal.tsx
  frontend/src/app/admin/studyContent/modal/contentDeleteModal.tsx
  frontend/src/app/admin/studyContent/modal/contentDetailModal.tsx
  frontend/src/app/admin/studyContent/modal/contentEditModal.tsx
  frontend/src/app/admin/studyContent/page.tsx
  frontend/src/app/admin/studyContent/sidebar.tsx
  frontend/src/app/community/[postId]/page.tsx
  frontend/src/app/interview/all/page.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
Labels: Refactor

#135 Feat/#132
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/community/page.tsx
  frontend/src/app/studyContent/memoList/[selectedContentId]/page.tsx
  frontend/src/app/studyContent/studyContentBody.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
Labels: Refactor

#139 Feat/#136
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/OpenAiService.java
  frontend/.gitignore
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/app/techInterview/evaluation/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#140 Feat/#102 구독 결제 기능 구현
  backend/build.gradle
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/dto/MemberDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/SubscriptionPlan.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/dto/reqestDto/PaymentRequestDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/dto/responseDto/PaymentResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/entity/Order.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/repository/OrderRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/service/PaymentService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/PortOneConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/dataInit/StudyContentDataInit.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
  frontend/package.json
  frontend/src/app/chat/ChatWidget.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/result/page.tsx
  frontend/src/app/payment/store/paymentStroe.tsx
  frontend/src/app/styles/payment.module.css
  frontend/src/global.d.ts
Labels: Feature

#142 Feat/#141
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/entity/Member.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/scheduler/SubscribeScheduler.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/member/service/MemberService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/openAI/InterviewAIController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/service/PaymentService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/customAnnotation/PremiumAccess.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/customAnnotation/SubscriptionPlanChecker.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
  frontend/src/app/api/techInterview/evaluation/route.ts
  frontend/src/app/api/techInterview/next/route.ts
  frontend/src/app/api/techInterview/start/route.ts
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/result/page.tsx
  frontend/src/app/techInterview/TechInterviewChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Feature, Fix, Refactor

#145 [Fix] 채팅 딜레이 버그 수정
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/mail/EmailService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/AsyncConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/SchedulerConfig.java
  backend/src/main/resources/application.yml
  frontend/src/app/chat/ChatWidget.tsx
  frontend/src/app/chat/FlotingChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#146 feat: 채팅 시스템 WebSocket 적용 및 Redis 연동
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatPublisher.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatSubscriber.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/RedisConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/config/WebSocketConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/websocket/WebSocketEventListener.java
  backend/src/main/resources/application.yml
Labels: Feature

#150 Feat/#144
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/controller/NewsController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobsDetailDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/NewResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/entity/NewsItem.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/service/NewsService.java
  backend/src/main/java/com/java/NBE4_5_1_7/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
  frontend/src/app/components/Header.tsx
  frontend/src/app/news/page.tsx
Labels: Feature

#154 [Fix] 유실된 코드 일부 복원 및 시스템 메세지 추가
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  frontend/src/app/chat/FlotingChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#155 Feat/#151 채용공고 단건조회 API 구현
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/controller/NewsController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobResponseDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/dto/responseDto/JobsDetailDto.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/service/NewsService.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/payment/service/PaymentService.java
Labels: Feature

#158 fix: 메시지의 시간을 한국 기준으로 변경
  backend/src/main/java/com/java/NBE4_5_1_7/domain/mail/EmailService.java
  backend/src/main/resources/templates/email-template.html
  frontend/src/app/admin/chat/page.tsx
Labels: Fix

#161 Feat/#157 채용 공고 API - 프론트엔드
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/controller/NewsController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/news/service/NewsService.java
  frontend/src/app/news/[recrutPblntSn]/page.tsx
  frontend/src/app/news/jobs.tsx
  frontend/src/app/news/news.tsx
  frontend/src/app/news/page.tsx
Labels: Feature

#163 [Fix] 채팅 컴포넌트를 제일 상위로
  frontend/src/app/chat/FlotingChat.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: Fix

#173 fix: 고객센터 채팅 로직 수정
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/ChatController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/controller/GuestRoomController.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/model/ChatRoom.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/java/NBE4_5_1_7/domain/chat/service/ChatService.java
  frontend/src/app/admin/chat/page.tsx
  frontend/src/app/chat/FlotingChat.tsx
Labels: Fix

#175 refactor: 채팅 UI 수정
  frontend/src/app/chat/FlotingChat.tsx
Labels: Refactor
